# Generated by Django 5.0.4 on 2024-05-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
